# pretrained_model_name_or_path: stabilityai/stable-diffusion-xl-base-1.0
# pretrained_model_name_or_path: stablediffusionapi/realistic-vision-512
# pretrained_model_name_or_path: stablediffusionapi/juggernaut-xl

# pretrained_model_name_or_path: stablediffusionapi/juggernaut-xl-v7

pretrained_model_name_or_path = stabilityai/sdxl-turbo


pretrained_vae_model_name_or_path: madebyollin/sdxl-vae-fp16-fix
# 
# inference_prompt: A photo of a 50 years old man with curly hair.
# inference_prompt: RAW photo, a portrait photo of a shapely and sporty beautiful latina woman model with full lips and doube D bra size through cleavage in casual clothes, natural skin, 8k uhd, high quality, film grain, Fujifilm XT3

# inference_prompt: ultra realistic , hyper detail, portrait photo of a shapely and sporty beautiful latina woman model with full lips and doube D bra size through cleavage in casual clothes, natural (imperfect skin:1.8), cinematic lighting, magic neon, dark red city, Canon EOS R3, nikon, f/1.4, ISO 200, 1/160s, 8K, RAW, unedited, symmetrical balance, in-frame, 8K
inference_prompt: ultra realistic , hyper detail, photo of a shapely and full lips and doube D bra size, sporty beautiful latina woman model with cleavage in casual clothes, (((imperfect skin:1.8))),  Canon EOS R3, nikon, f/1.4, ISO 200, 1/160s, 8K, RAW, unedited, symmetrical balance, in-frame, 8K, grained, -CGI, -anime, -painting
# negative_prompt: (deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime:1.4), text, close up, cropped, out of frame, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck
learnable_property: object
initializer_token: cha
placeholder_token: <$V$>
repeats: 1
save_as_full_pipeline: true
validation_prompt: A photo of <$V$>
caption_column: text
resolution: 1024
random_flip: true
train_batch_size: 1
num_train_epochs: 1
# checkpointing_steps: 500
checkpointing_steps: 5

learning_rate: 0.00003
lr_scheduler: constant
lr_warmup_steps: 0
mixed_precision: bf16
seed: 42
character_name: luciavarelaarroyo
output_dir: ./experiments
train_data_dir: ./loop_images
backup_data_dir_root: ./data # Your dataset backup folder
# lora_ckpt_dir: checkpoint-1200
# max_train_steps: 500
max_train_steps: 5

num_of_generated_img: 6
# num_of_generated_img: 128
dmin_c: 3
# dsize_c: 20    
dsize_c: 3    
infer_steps: 35
adam_epsilon: 0.000000001
adam_weight_decay: 0.0001
adam_beta1: 0.9
adam_beta2: 0.99
max_loop: 1
convergence_scale: 0.6 # 80% in the paper

# inherited from origin, no need to change
gradient_accumulation_steps: 1
report_to: tensorboard
push_to_hub: false
num_vectors: 1
enable_xformers_memory_efficient_attention: false
rank: 4
train_text_encoder: false
allow_tf32: false
scale_lr: false
use_8bit_adam: false 
# use_8bit_adam: true #TODO cange to False

text_inv: false # text_inv only
lora: false     # lora
center_crop: true
dataloader_num_workers: 0
noise_offset: 0
max_grad_norm: 1.0
num_validation_images: 4
validation_epochs: 1